version: '2.1'
services:
    selenium:
        image: selenium/standalone-chrome:3.0.1-dysprosium

    wdio:
        links:
            - selenium:selenium
        volumes:
            - ${HUMBLE_DATA}/screenshot:/usr/src/screenshot
            - ${HUMBLE_DATA}/reports:/usr/src/reports
