version: '2.1'
services:
    selenium:
        image: selenium/standalone-chrome:3.0.1-dysprosium

    wdio:
        links:
            - selenium:selenium
        volumes:
            - ${HUMBLE_DATA}/test-screenshots:/usr/src/screenshots
            - ${HUMBLE_DATA}/test-reports:/usr/src/reports
        environment:
            SELENIUM_HOST: selenium
            SELENIUM_PORT: 4444
            SELENIUM_BROWSER: chrome
